name: ChestLock
author: DaytonJWatson
description: Easy Chestlock
version: 0.1.4
api-version: 1.19
main: me.daytonjwatson.ChestLock.Main
commands:
  chestlock:
    description: Chestlock command